name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
- type: checkboxes
  attributes:
    label: Consent
    options:
    - label: I verified that there is no open/closed issue for the same subject.
      required: true
- type: textarea
  attributes:
    label: Feature
    description: Describe the feature you'd like
  validations:
    required: true
- type: textarea
  attributes:
    label: Solution
    description: Describe the solution you'd like
  validations:
    required: false
